services:
  - type: web
    name: youtube-downloader
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y ffmpeg && \
      pip install -r requirements.txt
    startCommand: python app.py
